version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: social_rd_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
